# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='signal',
            name='source_user',
            field=models.CharField(blank=True, max_length=140, verbose_name='Source Username'),
        ),
        migrations.AddField(
            model_name='signal',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='Is Verified?'),
        ),
        migrations.AddField(
            model_name='signal',
            name='type',
            field=models.ManyToManyField(related_name='signal', related_query_name='signals', to='signals.SignalType'),
        ),
    ]
