# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_auto_20170909_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='type',
            new_name='types',
        ),
    ]
