# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_auto_20170909_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Not showed to the public.', verbose_name='Private Notes'),
        ),
    ]
