# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_signal_private_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='social_network',
            field=models.CharField(choices=[('TWTR', 'Twitter'), ('INSTA', 'Instagram'), ('FB', 'Facebook')], default='TWTR', max_length=6),
        ),
    ]
