# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_signal_social_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='slug',
            field=models.SlugField(default='0', max_length=1024, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signal',
            name='types',
            field=models.ManyToManyField(related_name='signals', related_query_name='signals', to='signals.SignalType'),
        ),
    ]
