# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_auto_20170910_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='slug',
            field=models.SlugField(max_length=1024, unique=True, verbose_name='Slug'),
        ),
    ]
